name: final_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  floor: ^1.1.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  encrypted_shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.4
  floor_generator: ^1.1.0
  dartdoc: ^8.0.7

flutter:
  uses-material-design: true
  generate: true

